### ISSUE TITLE
mk_prepare_receptor.py: 'load_atom_params' need to suffixed with .json

### ISSUE THREAD

**Issue by frgoe003** [forlilab/Meeko#251]
Hello, I'm trying to use the mk_prepare_receptor.py of Meeko 0.6.0: 

`mk_prepare_receptor.py --read_pdb {receptor_pdb_path} -o {pdbqt_path} --allow_bad_res`

But always get this error:

```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/docking/bin/mk_prepare_receptor.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/miniconda3/envs/docking/lib/python3.11/site-packages/meeko/cli/mk_prepare_receptor.py", line 476, in main
    mk_prep = MoleculePreparation()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/docking/lib/python3.11/site-packages/meeko/preparation.py", line 142, in __init__
    self.atom_params = self.get_atom_params(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/docking/lib/python3.11/site-packages/meeko/preparation.py", line 356, in get_atom_params
    raise ValueError(msg)
ValueError: names passed to 'load_atom_params' need to suffixed with .json
or be the unsuffixed basename of a JSON file in /home/fgoerlich/miniconda3/envs/docking/lib/python3.11/site-packages/meeko/data/params.
name was ad4_types

```

is this something I need to fix on my side? If so, how?

**Comment by rwxayheee** [comment]
Hi @frgoe003 
This seems to be the same issue https://github.com/forlilab/Meeko/issues/250
We have described and fixed it https://github.com/forlilab/Meeko/pull/241 
We have merged the fix but it isn’t released yet. For the time being, you can install from a download of this repository:

```
git clone https://github.com/forlilab/Meeko.git
cd Meeko; pip install .; cd ..
```

**Comment by frgoe003** [comment]
Thanks for the quick reply! I tried that, but the error persists. Do I need to install from another branch?

**Comment by frgoe003** [comment]
`git clone -b develop https://github.com/forlilab/Meeko/ `
seems to work

**Comment by diogomart** [comment]
Fixed in v0.6.1, which are now available on PyPI and conda-forge. Nothing wrong with installing from develop branch though.
